name = input("What is your name? ")
age = int(input("What is your age? "))
species = input("What species are you? ")
hometown = input("What is your hometown? ")
occupation = input("What is your occupation? ")

height = float(input("What is your height in feet? "))
hair_color = input("What is your hair color? ")
eye_color = input("What is your eye color? ")
clothing_style = input("What is your clothing style? ")
identifying_feature = input("What is your identifying feature? ")

special_talent = input("What is your special talent? ")
biggest_fear = input("What is your biggest fear? ")
best_friend = input("Who is your best friend? ")
personal_goal = input("What is your personal goal? ")
favorite_saying = input("What is your favorite saying? ")

def character_profile(name, age, species, hometown, occupation, height, hair_color, eye_color, clothing_style, identifying_feature, special_talent, biggest_fear, best_friend, personal_goal, favorite_saying):
    print("Name: " + name)
    print("Age: " + str(age))
    print("Species: " + species)
    print("Hometown: " + hometown)
    print("Occupation: " + occupation)
    print("Height: " + str(height) + " feet")
    print("Hair Color: " + hair_color)
    print("Eye Color: " + eye_color)
    print("Clothing Style: " + clothing_style)
    print("Identifying Feature: " + identifying_feature)
    print("Special Talent: " + special_talent)
    print("Biggest Fear: " + biggest_fear)
    print("Best Friend: " + best_friend)
    print("Personal Goal: " + personal_goal)
    print("Favorite Saying: " + favorite_saying)

print(character_profile(name, age, species, hometown, occupation, height, hair_color, eye_color, clothing_style, identifying_feature, special_talent, biggest_fear, best_friend, personal_goal, favorite_saying))