countdown = input("how many seconds are left until launch")
oxygen_tanks = input("how many oxygen tanks do we have for the mission")
food_packs = input("how many food packs do we have")
water_packs = input(" how many water packs do we have")
print("----------------------------------------------")
print(countdown + countdown)
print(oxygen_tanks + oxygen_tanks)
print(food_packs + food_packs)
print(water_packs + water_packs)
oxygen_tanks = input("confirm water tank supply")
print("---------------------------------------------")
print(countdown + countdown)
print(oxygen_tanks + oxygen_tanks)
print(food_packs + food_packs)
print(water_packs + water_packs)